import { Badge, Box, Container, Flex, Grid, GridItem, Heading, HStack, Text, VStack } from '@chakra-ui/react'
import Head from 'next/head'
import { Card } from "../components/Card"

export default function Home() {
  return (
    <VStack>
      <Head>
        <title>DAO Governance</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex mt={10} justifyContent={'center'}>
        <Heading fontFamily={'mono'} fontWeight={600}>Governance Dashboard</Heading>
      </Flex>
      <Grid templateColumns='repeat(3, 1fr)' gap={6} mt={10}>
        <GridItem><Card subgraphName={"messari/ens-governance"} /></GridItem>
        {/* <GridItem><Card subgraphName={"messari/fei-governance"} /></GridItem> */}
      </Grid>
    </VStack>
  )
}
